const recipes = [
  {
    id: 1,
    image: 'https://via.placeholder.com/300x200.png?text=Sausage+Cream+Cheese+Dip',
    title: 'Sausage Cream Cheese Dip',
    author: 'THE TWO BITE CLUB',
    rating: 5,
    reviews: '1k',
    inspiration: 'Your Weekend Recipe Inspiration',
    original: false,
  },
  {
    id: 2,
    image: 'https://via.placeholder.com/300x200.png?text=Asian+Recipes',
    title: 'Asian Recipes',
    author: '',
    rating: 0,
    reviews: '',
    inspiration: '',
    original: false,
  },
  {
    id: 3,
    image: 'https://via.placeholder.com/300x200.png?text=Traeger+Smoked+Spatchcock+Chicken',
    title: 'Traeger Smoked Spatchcock Chicken',
    author: 'YUMMLY',
    rating: 5,
    reviews: '610',
    inspiration: 'Your Weekend Recipe Inspiration',
    original: false,
  },
  {
    id: 4,
    image: 'https://via.placeholder.com/300x200.png?text=Chicken+Stuffed+Peppers',
    title: 'Chicken Stuffed Peppers',
    author: 'THE COOKIN CHICKS',
    rating: 4,
    reviews: '308',
    inspiration: 'Your Weekend Recipe Inspiration',
    original: false,
  },
  {
    id: 5,
    image: 'https://via.placeholder.com/300x200.png?text=One+Pot+Cajun+Chicken+and+Sausage+Alfredo',
    title: 'One Pot Cajun Chicken and Sausage Alfredo',
    author: 'NO. 2 PENCIL',
    rating: 5,
    reviews: '5k',
    inspiration: 'Your Weekend Recipe Inspiration',
    original: false,
  },
  {
    id: 6,
    image: 'https://via.placeholder.com/300x200.png?text=French+Onion+Chicken+Skillet',
    title: 'French Onion Chicken Skillet',
    author: 'COOKING FOR KEEPS',
    rating: 5,
    reviews: '964',
    inspiration: 'Your Weekend Recipe Inspiration',
    original: false,
  },
  {
    id: 7,
    image: 'https://via.placeholder.com/300x200.png?text=Cheesy+Garlicky+Breadsticks',
    title: 'Cheesy Garlicky Breadsticks',
    author: 'LORD BYRON\'S KITCHEN',
    rating: 5,
    reviews: '7k',
    inspiration: 'Popular On Yummly',
    original: false,
  },
  {
    id: 8,
    image: 'https://via.placeholder.com/300x200.png?text=Philly+Cheesesteak+Sandwiches',
    title: 'Philly Cheesesteak Sandwiches',
    author: 'YUMMLY',
    rating: 5,
    reviews: '322',
    inspiration: '',
    original: true,
  },
];

export default recipes;